### ISSUE TITLE
『SDOI2018』旧试题 | Jason的小屋

### ISSUE THREAD

**Issue by jason-fxz** [jason-fxz/jason-fxz.github.io#26]
https://blog.jasonfan.ml/2021/04/28/SDOI-%E6%97%A7%E8%AF%95%E9%A2%98/ 

 题意 luogu - P4619 [SDOI2018]旧试题 ∑i=1A∑j=1B∑k=1Cσ0(ijk)\sum_{i=1}^A\sum_{j=1}^B\sum_{k=1}^C \sigma_0(ijk) i=1∑A​j=1∑B​k=1∑C​σ0​(ijk) σ0(x)\sigma_0(x)σ0​(x) 表 xxx 约数个数。 多测 T≤10T\le 10T≤10，1≤∑max⁡(A,B,C)≤

**Comment by freewh2005** [comment]
我是@jasonfan的小迷妹，hoho,让我们一起啊掉jasonfan!
